### ISSUE TITLE
Module does not intsall under prestashop 1.7

### ISSUE THREAD

**Issue by avagarwal** [PrestaShop/paymentexample#4]
This module does not install.

**Comment by Quetzacoalt91** [comment]
![capture d ecran 2016-12-12 a 08 44 43](https://cloud.githubusercontent.com/assets/6768917/21092986/44f03e6a-c047-11e6-9748-fd81d2a84d4c.png)


It does, when you download the zip from GitHub, you have to remove `-master` from the folder name in the zip.

Best regards
