### ISSUE TITLE
iframe - payment

### ISSUE THREAD

**Issue by avagarwal** [PrestaShop/paymentexample#5]
Selecting iframe payment just refreshes the page, no iframe is shown.

**Comment by pangteypiyush** [comment]
CORS

**Comment by ysilvela** [comment]
Changing src by the same domain happens the same issue.

**Comment by davidgv88** [comment]
Fixed! Pull Request #3

**Comment by swja** [comment]
The src of iframe isnt recognize in the tpl file and it pass to the navigtator as src (unknown)

**Comment by brianmituka** [comment]
Whi has succesfully managed to use their iframe as a payment gateway? I'm having issues with validating an order and showing it in the back office as an order and also passing the amount to the Iframe @davidgv88

**Comment by Droidbuster** [comment]
I have download and also installed module in my preatashop but on the front end nothing is showing but at the payment module i have enabled .
