### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by watio** [PrestaShop/paymentexample#6]
Hello, tank for this exemple. I have this error when i submit the payment form.
[PrestaShopException]

No template found for payment_return.tpl
at line 68 in file classes/Smarty/TemplateFinder.php

63.                     return $tpl;
64.                 }
65.             }
66.         }
67. 
68.         throw new PrestaShopException('No template found for '.$template);
69.     }
70. 
71.     private function getTemplateHierarchy($template, $entity, $id)
72.     {
73.         $entity = basename($entity);

Can you help me please ?

**Comment by lfirek** [comment]
Hello,

Yep, I know this is really expired topic but without answer.

`
$this->setTemplate('module:paymentexample/views/templates/front/payment_return.tpl');
`

**Comment by Quetzacoalt91** [comment]
Fixed by #3, thanks guys
